### ISSUE TITLE
[RES addon Problem] It doesn't filter next page that got autoloaded 

### ISSUE THREAD

**Issue by tayser1** [nickgaya/rededup#1]
Reddit Enhancement Suite (RES) addons Setting (neverEndingReddit) doesn't let "redudup" filter the next Pages that got automatically loaded. Only the first Page gets scanned by addon.
reproducing:
RES Addon -> Preference -> (neverEndingReddit) ON -> autoLoad ON

**Comment by nickgaya** [comment]
Thanks for your report!  Currently the extension only scans the page at load time. It has not been designed or tested for compatibility with other addons such as Reddit Enhancement Suite.  However, given the popularity of RES this seems like a reasonable feature request, so I'll consider adding support for it in the future.

**Comment by tayser1** [comment]
It would be nice to add an option to manually deduplicate  or to rescan the whole page then dedup

**Comment by da2x** [comment]
Far from perfect, but this should get the job done:

    const resizeObserver = new ResizeObserver(run_deduplication_function_when_body_changes_size);
    resizeObserver.observe(document.body);

The deduplicator will need to change to avoid processing the same item twice. Just set an attribute on processed items so it knows to skip it in future iterations.

**Comment by nickgaya** [comment]
I have added support for "Never Ending Reddit" as part of Version 1.2, which has just been released to the Firefox and Chrome web extension stores.  Feel free to open a new issue if you encounter problems or have other suggestions.
